---

- name: provision database
  command: bin/server -c config/{{ config_file }} -provision chdir={{ chdir }}
  ignore_errors: yes
  tags: service

- template: src=service.conf.j2 dest=/etc/init/{%= name %}.conf mode=0644
  when: env == 'production'

- service: name={%= name %} enabled=yes
  when: env == 'production'
