---

- hosts: localhost
  connection: local
  gather_facts: false
  sudo: no

  pre_tasks:
  - name: launch cloudformation stack
    cloudformation: >
      stack_name="{%= name %}-dev" state=present
      region=us-east-1 disable_rollback=false
      template=files/cloudformation.json
    register: stack
    tags: cloudformation

  roles:
  - { role: config, config_file: "../config/development.json" }

  vars_files:
    - vars/dev.yml
