---

- hosts: all
  roles:
   - role: common
   - { role: build, chdir: '/tmp/{%= name %}' }
   - { role: service, config_file: 'production.json', chdir: '/opt/services/{%= name %}' }
  vars_files:
    - vars/prod.yml
